server:
  port: 8010
spring:
  application:
    name: user-microservice
  datasource:
    name: datasource
    url: jdbc:mysql://115.159.31.229:3306/cloud_mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    #url: jdbc:mysql://172.17.0.13:3306/cloud_mall?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: root
    password: CloudBase123!@#
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      max-active: 20
      min-idle: 1
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
  redis:
    database: 0
    #host: 115.159.31.229
    host: 172.17.0.13
    port: 6379
    password: CloudBase123!@#
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0
eureka:
  client:
    service-url:
      #defaultZone : http://115.159.31.229:8000/eureka
      #defaultZone : http://172.17.0.13:8000/eureka
      defaultZone : http://localhost:8000/eureka
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql